//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.14 at 06:03:31 PM VET 
//

package com.minotauro.user.xml.prof;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}priv" maxOccurs="unbounded"/>
 *         &lt;element ref="{}role" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"description", "priv", "role"})
@XmlRootElement(name = "prof")
public class Prof {

  @XmlElement(required = true)
  protected Description description;
  @XmlElement(required = true)
  protected List<Priv> priv;
  @XmlElement(required = true)
  protected List<Role> role;
  @XmlAttribute(required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String name;

  /**
   * Gets the value of the description property.
   * 
   * @return
   *     possible object is
   *     {@link Description }
   *     
   */
  public Description getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *     allowed object is
   *     {@link Description }
   *     
   */
  public void setDescription(Description value) {
    this.description = value;
  }

  /**
   * Gets the value of the priv property.
   * 
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the priv property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getPriv().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Priv }
   * 
   * 
   */
  public List<Priv> getPriv() {
    if (priv == null) {
      priv = new ArrayList<Priv>();
    }
    return this.priv;
  }

  /**
   * Gets the value of the role property.
   * 
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the role property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getRole().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Role }
   * 
   * 
   */
  public List<Role> getRole() {
    if (role == null) {
      role = new ArrayList<Role>();
    }
    return this.role;
  }

  /**
   * Gets the value of the name property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setName(String value) {
    this.name = value;
  }

}
